apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  labels:
    name: jupyter-notebook
spec:
  # The LoadBalancer type is required to get a public IP
  # address when running on Google Container Engine.
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
  selector:
    name: jupyter-notebook
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: jupyter-notebook
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    name: jupyter-notebook
  template:
    metadata:
      labels:
        name: jupyter-notebook
    spec:
      containers:
        - name: jupyter-notebook
          image: ogrisel/distributed:latest
          args: ["start-notebook.sh"]
          ports:
            - name: http
              containerPort: 8888
          volumeMounts:
            - mountPath: /work/docker-distributed
              name: docker-distributed-repo
      securityContext:
        fsGroup: 1000
      volumes:
        - name: docker-distributed-repo
          gitRepo:
            repository: "https://github.com/ogrisel/docker-distributed"
